control/urls.py
from django.urls import path
from control import views

app_name = "control"
urlpatterns = [
    path("", views.index, name="index"),
    path("takeoff/", views.takeoff, name="takeoff"),
    path("land/", views.land, name="land"),
    path("forward/", views.forward, name="forward"),
    path("backward/", views.backward, name="backward"),
    path("left/", views.left, name="left"),
    path("right/", views.right, name="right"),
    path("turn_left/", views.turn_left, name="turn_left"),
    path("turn_right/", views.turn_right, name="turn_right"),
    path("picture/", views.picture, name="picture"),
    path("emergency_stop/", views.emergency_stop, name="emergency_stop"),
    path("show/", views.show, name="show"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("control/", include("control.urls")),
]

control/models.py
from django.db import models

# Create your models here.

control/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from djitellopy import Tello
import cv2
import time


tello = Tello()


def takeoff(request):
    print("taking off")

    tello.takeoff()
    battery = tello.get_battery()
    print(battery)
    return HttpResponseRedirect("/control")


def land(request):
    print("landing")
    tello.land()
    return HttpResponseRedirect("/control")


def forward(request):
    print("forward")
    tello.move_forward(30)
    return HttpResponseRedirect("/control")


def backward(request):
    print("backward")
    tello.move_back(30)
    return HttpResponseRedirect("/control")


def left(request):
    print("left")
    tello.move_left(30)
    return HttpResponseRedirect("/control")


def right(request):
    print("right")
    tello.move_right(30)
    return HttpResponseRedirect("/control")


def turn_left(request):
    tello.rotate_counter_clockwise(90)
    return HttpResponseRedirect("/control")


def turn_right(request):
    tello.rotate_clockwise(90)
    return HttpResponseRedirect("/control")


def picture(request):
    tello.streamon()
    frame_read = tello.get_frame_read()
    cv2.imwrite("picture.png", frame_read.frame)  # type:ignore
    response = FileResponse(open("picture.png", "rb"), as_attachment=True)
    return response


def show(request):
    tello.takeoff()
    time.sleep(1)
    tello.land()
    return HttpResponseRedirect("/control")


def emergency_stop(request):
    tello.emergency()
    return HttpResponseRedirect("/control")


def flip_forward(request):
    # need to be tested in large area , no idea about it's behavior
    tello.flip_forward()
    return HttpResponseRedirect("/control")


def flip_backward(request):
    tello.flip_back()
    return HttpResponseRedirect("/control")


def index(request):
    try:
        tello.connect(wait_for_state=False)
        battery = tello.get_battery()
        # TODO: stay connected after drone if off, need server restart
        return render(
            request,
            "control/index.html",
            context={"connected": True, "battery": battery},
        )
    except:
        return render(
            request, "control/index.html", context={"connected": False, "battery": 0}
        )

control/templates/control/index.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />

        <title>Drone Controls</title>
        <style>
            a {
                color: inherit;
                text-decoration: none;
                width: 100%;
            }

            body {
                font-family: sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                background-color: #f4f4f4;
            }

            .controls-container {
                border: 1px solid #ccc;
                padding: 20px;
                border-radius: 8px;
                background-color: #fff;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
                text-align: center;
            }

            .button-grid {
                display: grid;
                grid-template-columns: repeat(2, 1fr);
                gap: 10px;
                margin-bottom: 20px;
            }

            button {
                padding: 10px 15px;
                border: none;
                border-radius: 5px;
                background-color: #007bff;
                color: white;
                cursor: pointer;
                width: 100%;
            }

            button:hover {
                background-color: #0056b3;
            }

            .slider-container {
                margin-bottom: 10px;
            }

            .slider-container label {
                display: block;
                margin-bottom: 5px;
            }
            .emergency_button {
                padding: 10px 15px;
                border: none;
                border-radius: 5px;
                background-color: #e6913c;
                color: white;
                cursor: pointer;
                margin-top: 10px;
            }
            .emergency_button:hover {
                background-color: #e66c3c;
            }
            .picture_button {
                padding: 10px 15px;
                border: none;
                border-radius: 5px;
                background-color: #67ad51;
                color: white;
                cursor: pointer;
            }
            .picture_button:hover {
                background-color: #598a3d;
            }
            input[type="range"] {
                width: 100%;
            }

            #status-display {
                margin-top: 20px;
                padding: 10px;
                border: 1px solid #ddd;
                border-radius: 5px;
                background-color: #f9f9f9;
            }
        </style>
    </head>
    <body>
        <div class="controls-container">
            <h2>
                Drone Controls {% if connected %}
                <h3 style="color: green">connected</h3>
                {%else%}
                <h3 style="color: red" }>not connected</h3>
                {%endif%}
            </h2>

            <div class="button-grid">
                <a href="{%url 'control:takeoff' %}"
                    ><button id="takeoff">
                        <i class="fas fa-plane-departure"></i>&nbsp;Takeoff
                    </button></a
                >
                <a href="{% url 'control:land' %}"
                    ><button id="land">
                        <i class="fas fa-plane-arrival"></i>&nbsp;Land
                    </button></a
                >
                <a href="{% url 'control:forward' %}"
                    ><button id="forward">
                        <i class="fas fa-arrow-up"></i>&nbsp;Forward
                    </button></a
                >
                <a href="{% url 'control:backward' %}"
                    ><button id="backward">
                        <i class="fas fa-arrow-down"></i>&nbsp;Backward
                    </button></a
                >
                <a href="{% url 'control:left' %}"
                    ><button id="left">
                        <i class="fas fa-arrow-left"></i>&nbsp;Left
                    </button></a
                >
                <a href="{% url 'control:right' %}"
                    ><button id="right">
                        <i class="fas fa-arrow-right"></i>&nbsp;Right
                    </button></a
                >
                <a href="{% url 'control:turn_left' %}"
                    ><button id="turn_left">
                        <i class="fas fa-undo"></i>&nbsp;Turn Left
                    </button></a
                >
                <a href="{% url 'control:turn_right' %}"
                    ><button id="turn_right">
                        <i class="fas fa-redo"></i>&nbsp;Turn right
                    </button></a
                >
            </div>
            <a href="{% url 'control:show' %}">
                <button id="picture" style="margin-bottom: 15px">
                    takeoff + land
                </button></a
            >
            <a
                href="{% url 'control:picture' %}"
                target="_blank"
                rel="noopener noreferrer"
            >
                <button id="picture" class="picture_button">
                    <i class="fa-solid fa-camera"></i>&nbsp;Take a picture
                </button></a
            >
            <a href="{%url 'control:emergency_stop' %}">
                <button id="emergency" class="emergency_button">
                    <i class="fas fa-exclamation-triangle"></i>&nbsp;Emergency
                    Stop
                </button>
            </a>
            <div id="status-display">battery: {{battery}}</div>
        </div>
    </body>
</html>